PewterCity_Bug_Gym_Text_TakashiIntro::
    .string "I'm the ninja master TAKASHI.\p"
    .string "SURPRISE ATTACK!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PewterCity_Bug_Gym_Text_TakashiDefeat::
    .string "Nooooo, I lost…\p"
    .string "As proof of your victory, I confer\n"
    .string "on you this…the official POKéMON\l"
    .string "LEAGUE JITTERBADGE.\p"
    .string "{FONT_NORMAL}{PLAYER} received the JITTERBADGE\n"
    .string "from TAKASHI!{PAUSE_MUSIC}{PLAY_BGM}{MUS_OBTAIN_BADGE}{PAUSE 0xFE}{PAUSE 0x56}{RESUME_MUSIC}\p"
    .string "{FONT_MALE}The JITTERBADGE is\n"
    .string "proof of besting me.\p"
    .string "So wear it with pride!$"

PewterCity_Bug_Gym_Text_TakashiPostBattle::
    .string "I must continue to hone my techniques\n"
    .string "so that next time…\p"
    .string "I will be victorious!$"

PewterCity_Bug_Gym_Text_MaruIntro::
    .string "You chose the wrong path since\n"
    .string "you'll never get past me!$"

PewterCity_Bug_Gym_Text_MaruDefeat::
    .string "Argh!\p"
    .string "No way you beat me fairly.\n"
    .string "I bet you cheated just like TAKASHI!$"

PewterCity_Bug_Gym_Text_MaruPostBattle::
    .string "TAKASHI always uses some weird tricks\n"
    .string "to win.\p"
    .string "I think it's cheating!$"

PewterCity_Bug_Gym_Text_AntiBugAdvice::
    .string "This gym uses BUG-type POKéMON.\p"
    .string "The're weak to FLYING, ROCK\n"
    .string "and FIRE.\p"
    .string "Just watch out for their\n"
    .string "tricky switching techniques.$"

PewterCity_Bug_Gym_Text_NiceAntiNinjaMoves::
    .string "You didn't let their tricks\n"
    .string "confuse you. Well done!$"

PewterCity_Bug_Gym_Text_GymStatue::
    .string "PEWTER BUG POKéMON GYM\n"
    .string "LEADER: TAKASHI\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

PewterCity_Bug_Gym_Text_GymStatuePlayerWon::
    .string "PEWTER BUG POKéMON GYM\n"
    .string "LEADER: TAKASHI\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"
